#!/usr/bin/env python3
"""
Weekly Portfolio Summary
------------------------
Reads portfolio-memory.json and outputs a markdown summary of the current week's activity.
Output goes to GitHub Actions step summary ($GITHUB_STEP_SUMMARY) for visibility in the repo.

Usage:
    python scripts/weekly-summary.py >> $GITHUB_STEP_SUMMARY
    python scripts/weekly-summary.py  # prints to stdout for local preview
"""

import json
from pathlib import Path
from datetime import date, timedelta

ROOT = Path(__file__).parent.parent
MEMORY_FILE = ROOT / "portfolio-memory.json"


def get_current_iso_week():
    today = date.today()
    return f"{today.year}-W{today.isocalendar()[1]:02d}"


def main():
    with open(MEMORY_FILE) as f:
        memory = json.load(f)

    current_week = get_current_iso_week()
    projects = memory.get("projects", [])
    weekly_log = memory.get("weekly_log", [])

    # Find this week's log entry
    this_week = next((w for w in weekly_log if w.get("week") == current_week), None)

    # All Claude builds
    claude_builds = [p for p in projects if p.get("category") == "claude-build"]
    active_builds = [p for p in claude_builds if p.get("status") in ("active", "in-progress")]

    lines = []
    lines.append(f"# Portfolio Weekly Update — {current_week}")
    lines.append(f"\n**Owner:** {memory.get('owner', 'Joshua McKenzie German')}")
    lines.append(f"**Last Updated:** {memory.get('last_updated', 'Unknown')}")
    lines.append(f"**Portfolio:** [{memory.get('portfolio_url', '')}]({memory.get('portfolio_url', '')})")

    lines.append("\n---\n")

    if this_week:
        lines.append(f"## This Week ({this_week.get('date_range', current_week)})")
        lines.append(f"\n{this_week.get('summary', 'No summary provided.')}")
        touched = this_week.get("projects_touched", [])
        if touched:
            lines.append(f"\n**Projects touched this week:** {', '.join(touched)}")
        notes = this_week.get("session_notes", "")
        if notes:
            lines.append(f"\n> {notes}")
    else:
        lines.append(f"## This Week ({current_week})")
        lines.append("\n_No log entry for this week yet. Add one to `portfolio-memory.json` → `weekly_log`._")

    lines.append("\n---\n")
    lines.append(f"## Claude Code Builds ({len(claude_builds)} total)\n")

    for p in claude_builds:
        status_emoji = {"active": "✅", "in-progress": "🔨", "complete": "🏁", "archived": "📦"}.get(p.get("status", ""), "•")
        url = p.get("url") or p.get("github") or ""
        name_link = f"[{p['name']}]({url})" if url else p["name"]
        lines.append(f"### {status_emoji} {name_link}")
        lines.append(f"**Tag:** {p.get('tag', 'Project')} | **Status:** {p.get('status', '').title()} | **Started:** {p.get('date_started', 'Unknown')}")
        lines.append(f"\n{p.get('description', '')}\n")
        tools = p.get("tools", [])
        if tools:
            lines.append(f"**Stack:** {', '.join(tools)}\n")

    lines.append("\n---\n")
    lines.append(f"_Generated by Portfolio Memory System — {date.today().isoformat()}_")

    print("\n".join(lines))


if __name__ == "__main__":
    main()
